Project project_name {
  database_type: 'PostgreSQL'
  Note: 'Description of the project'
}

Table products {
  id int [pk, increment]
  location int [ref: > locations.id]
  active int [Default: 1]
  name varchar [Note: 'a note']
}

Table orders {
  id int [pk]
  users_id int [not null, unique]
  cost decimal [default: 123.45]
  Note: 'Single line note'
  Note: '''
    This is a note across
    multiple lines
  '''
  Note: {
    'Note within braces.'
  }
  indexes {
    (id, users_id) [pk]  // composite primary key
  }
}

TableGroup ecommerce1 {
  table1
  table2
}

